# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import lab6_pb2 as lab6__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in lab6_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Lab6ServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/Lab6Service/add',
                request_serializer=lab6__pb2.addMsg.SerializeToString,
                response_deserializer=lab6__pb2.addReply.FromString,
                _registered_method=True)
        self.rawimage = channel.unary_unary(
                '/Lab6Service/rawimage',
                request_serializer=lab6__pb2.rawImageMsg.SerializeToString,
                response_deserializer=lab6__pb2.imageReply.FromString,
                _registered_method=True)
        self.dotproduct = channel.unary_unary(
                '/Lab6Service/dotproduct',
                request_serializer=lab6__pb2.dotProductMsg.SerializeToString,
                response_deserializer=lab6__pb2.dotProductReply.FromString,
                _registered_method=True)
        self.jsonimage = channel.unary_unary(
                '/Lab6Service/jsonimage',
                request_serializer=lab6__pb2.jsonImageMsg.SerializeToString,
                response_deserializer=lab6__pb2.imageReply.FromString,
                _registered_method=True)


class Lab6ServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rawimage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def dotproduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def jsonimage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Lab6ServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=lab6__pb2.addMsg.FromString,
                    response_serializer=lab6__pb2.addReply.SerializeToString,
            ),
            'rawimage': grpc.unary_unary_rpc_method_handler(
                    servicer.rawimage,
                    request_deserializer=lab6__pb2.rawImageMsg.FromString,
                    response_serializer=lab6__pb2.imageReply.SerializeToString,
            ),
            'dotproduct': grpc.unary_unary_rpc_method_handler(
                    servicer.dotproduct,
                    request_deserializer=lab6__pb2.dotProductMsg.FromString,
                    response_serializer=lab6__pb2.dotProductReply.SerializeToString,
            ),
            'jsonimage': grpc.unary_unary_rpc_method_handler(
                    servicer.jsonimage,
                    request_deserializer=lab6__pb2.jsonImageMsg.FromString,
                    response_serializer=lab6__pb2.imageReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Lab6Service', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Lab6Service', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Lab6Service(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lab6Service/add',
            lab6__pb2.addMsg.SerializeToString,
            lab6__pb2.addReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def rawimage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lab6Service/rawimage',
            lab6__pb2.rawImageMsg.SerializeToString,
            lab6__pb2.imageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def dotproduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lab6Service/dotproduct',
            lab6__pb2.dotProductMsg.SerializeToString,
            lab6__pb2.dotProductReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def jsonimage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Lab6Service/jsonimage',
            lab6__pb2.jsonImageMsg.SerializeToString,
            lab6__pb2.imageReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
